name: pawsafe
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  google_fonts: ^2.0.0
  path_provider: ^2.0.1
  cupertino_icons: ^1.0.2
  firebase_core: ^1.0.3
  firebase_auth: ^1.1.0
  cloud_firestore: ^1.0.5
  provider: ^5.0.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  image_picker: ^0.7.4
  firebase_storage: ^8.0.3
  firebase_analytics: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

